
# This code snippet was generated by the tinydolphin
"""
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(5))  # Output: 120
"""

# This code snippet was generated by Llama 2
"""
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
print(factorial(5))  # Output: 120
"""

# This code snippet was generated by Gemma 3
"""
def factorial(n):
  \"""
  Calculates the factorial of a non-negative integer.

  Args:
    n: A non-negative integer.

  Returns:
    The factorial of n (n!), which is the product of all positive integers 
    less than or equal to n.  Returns 1 if n is 0.
    Raises a ValueError if n is negative.
  \"""
  if n < 0:
    raise ValueError("Factorial is not defined for negative numbers")
  elif n == 0:
    return 1
  else:
    result = 1
    for i in range(1, n + 1):
      result *= i
    return result
print(factorial(5))  # Output: 120
"""